CREATE TYPE public.priority AS ENUM ('high', 'medium', 'low');
CREATE TYPE public.status AS ENUM ('pending', 'in-progress', 'completed');

CREATE TABLE public.todos (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title text NOT NULL,
    content text,
    footer text,
    priority public.priority DEFAULT 'medium'::public.priority NOT NULL,
    due_date timestamptz,
    task_img text,
    status public.status DEFAULT 'pending'::public.status NOT NULL,
    user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE,
    created_at timestamptz DEFAULT now() NOT NULL
);

COMMENT ON TABLE public.todos IS 'Todo list for users';

-- Enable RLS
ALTER TABLE public.todos ENABLE ROW LEVEL SECURITY;

-- Create policies
CREATE POLICY "Allow users to see their own todos" ON public.todos FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Allow users to insert their own todos" ON public.todos FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Allow users to update their own todos" ON public.todos FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "Allow users to delete their own todos" ON public.todos FOR DELETE USING (auth.uid() = user_id);
