name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  test-migrations:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Supabase CLI
        uses: supabase/setup-cli@v1

      - name: Start Supabase local environment
        run: supabase start

      - name: Verify migrations
        run: supabase db reset

      - name: Stop Supabase local environment
        run: supabase stop
